services:
  desktop-tailscale:
    network_mode: "host"
    image: ${DESKTOP_PLUGIN_IMAGE}
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - "tailscalestate:/var/lib/tailscale"
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  tailscalestate:
